version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4444:4444
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
